apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: queue
spec:
  type: bindings.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: route
    value: /receive