apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ca-engine
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: engine-app
  targetCPUUtilizationPercentage: 20