name: deploy-infrastructure
on:
  workflow_dispatch:
    inputs:
      deploymentName:
        description: 'Deployment name'     
        required: true
        default: 'dzrunner3'
      location:
        description: 'Location'     
        required: true
        default: 'northeurope'
permissions:
  id-token: write
  contents: read

jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: actions/checkout@v2
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Run az commands'
      run: |
        chmod +x ./deploy-infra.sh
        ./deploy-infra.sh ${{ github.event.inputs.deploymentName }} ${{ github.event.inputs.location }}